---
# handlers file for lighthouse-role
- name: NGINX | Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
  listen: start nginx

- name: NGINX | Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: reload nginx
