---
# tasks file for lighthouse-role
- name: NGINX | Add nginx apt-key
  become: true
  ansible.builtin.apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: NGINX | Add nginx apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb https://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx'
    state: present
    filename: nginx
    update_cache: true

- name: NGINX | Install
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  notify: start nginx

- name: NGINX | Create general config
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: reload nginx

- include_tasks: precheck.yml
  tags: [always]

- name: Lighthouse | Get from source
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location }}"

- name: Wait for nginx to get ready
  become: true
  ansible.builtin.pause:
    seconds: 30
    echo: false

- name: Lighthouse | Create Lighthouse config
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: reload nginx
